### ISSUE TITLE
not an issue just a request..

### ISSUE THREAD

**Issue by XeonG** [MirzaBeig/Post-Processing-Wireframe-Outlines#1]
heightmap contour lines? nopticed the depth image and wondered if this could this be modified to do acheive that, thinking of a minimap camera with top down camera or if anyone know's of something else for untity that could achieve that effect?

**Comment by MirzaBeig** [comment]
This might be possible, if the mesh itself is made very specifically so that it will be picked up by the edge detection via sharp depth offsets.

**Comment by XeonG** [comment]
I  was thinking the shader could be modified to put in an edge by distance from camera or world spacing.. like a line every 10units etc that was adjustable for Y cordinate

**Comment by MirzaBeig** [comment]
Another shader of mine does something similar. IIRC it calculates a repeating pattern via fract on world coordinates.
It may be useful to dig into in case you'd like to see how it's done or modify it.

https://github.com/MirzaBeig/Post-Processing-Scan

**Comment by XeonG** [comment]
aah I actually found something similar and modified there synthwave effect to just use the Y axis 

https://danielilett.itch.io/snapshot-shaders-pro-hdrp

pretty much the effect I wanted.. though would be good to have a much more fully featured one.. wouldn't mind being able to combine a few different efefcts or stack the synthwave effect with different masks/colors.. ie grid darker color, and the Y axis contour like lines in color.. but anyway kinda got something now
